import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/GlobalComp/Navbar.jsx";
import Footer from "../components/GlobalComp/Footer.jsx";

export const metadata: Metadata = {
  title: "Dreamation Resorts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/logo.png" />
        {/* Preload only if the font is used above-the-fold */}
        <link
          rel="preload"
          href="/fonts/Arial-BoldMT.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
